#!/bin/sh
#
# Copyright 2022, Marc S. Brooks (https://mbrooks.info)
# Licensed under the MIT license:
# http://www.opensource.org/licenses/mit-license.php

### BEGIN INIT INFO
# Provides:          grid-server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Open Simulator grid server
# Description:       Provides commands to manage your grid instance.
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/usr/bin/mono
SCRIPT=`basename $0`
BASEDIR=/usr/games
USER=games

. $BASEDIR/.grid-server

test -x $DAEMON || exit 0

start() {
  log_daemon_msg "Starting grid instance" "$DAEMON"
  start-stop-daemon --start --quiet --background --chdir $BASEDIR --chuid $USER --exec $DAEMON -- $BASEDIR/$RUNCMD
  log_end_msg $?
}

stop() {
  log_daemon_msg "Stopping grid instance" "$DAEMON"
  start-stop-daemon --stop --quiet --user $USER --oknodo --retry 5
  log_end_msg $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)

  log_failure_msg "Usage: $SCRIPT {start|stop|restart}"
  exit 1
esac

exit 0
